// Shared constants for hook content injection

export const MODEL_ROUTING_CONTENT = [
  "## Model Routing (auto-injected by plugin)",
  "",
  "BEFORE every `sessions_spawn`, select the right model:",
  "",
  "| Task Type | Model | Alias |",
  "|-----------|-------|-------|",
  "| OCR, extraction, audit, bulk ops, scraping, formatting | **Haiku** | `anthropic/claude-haiku` |",
  "| Dev, refactoring, code review, web research, writing | **Sonnet** | `anthropic/claude-sonnet-4` |",
  "| Complex reasoning, architecture, strategic decisions | **Opus** | `anthropic/claude-opus-4-6` |",
  "",
  "### Anti-patterns",
  "- ❌ NEVER spawn without specifying `model`",
  "- ❌ NEVER use Opus for execution tasks",
  "- ❌ NEVER do multiple web_fetch in Opus — delegate to Sonnet sub-agent",
  "- ❌ NEVER spawn 5+ sub-agents simultaneously without rate limit check",
  "",
  "### Context Budget",
  "- < 50%: normal operation",
  "- 50-70%: delegate reads to sub-agents",
  "- > 70%: switch to Sonnet if on Opus, delegate aggressively",
  "- > 85%: stop reading files, work from memory only",
].join("\n");
